[package]
name = "rust_nes_emu"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
paste = "1.0.9"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"

[dev-dependencies]
rand = "0.8.5"
sdl2 = "0.35.2"
